<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryCityAreaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::unprepared("INSERT INTO `countries` (`name`, `code`, `currency`) VALUES
        ('United Arab Emirates', 'AE', 'AED'),
        ('Oman', 'OM', 'OMR'),
        ('Saudi Arabia', 'SA', 'SAR'),
        ('Egypt', 'EG', 'EGP'),
        ('India', 'IN', 'INR'),
        ('Philippines', 'PH', 'PHP'),
        ('Kuwait', 'KW', 'KWD'),
        ('Bahrain', 'BH', 'BHD');");

        DB::unprepared("INSERT INTO `cities` (`name`, `code`, `country_id`) VALUES
        ('Dubai', 'DXB', 1),
        ('Sharjah', 'SHJ', 1),
        ('Abu Dhabi', 'AUH', 1),
        ('Ras Al Khaimah', 'RKT', 1),
        ('Fujairah', 'FJR', 1),
        ('Ajman', 'AJM', 1),
        ('Umm Al Qawain', 'UAQ', 1),
        ('Al Ain', 'AAN', 1),
        ('Al Dakhiliyah', NULL, 2),
        ('Al Batinah', NULL, 2),
        ('Al Batinah North Governorate', NULL, 2),
        ('Al Batinah South', NULL, 2),
        ('Dhofar', NULL, 2),
        ('Masqat', NULL, 2),
        ('Muhafazat ad Dakhiliyah', NULL, 2),
        ('Muhafazat Masqat', NULL, 2),
        ('Muhafazat Shamal al Batinah', NULL, 2),
        ('Muhafazat Zufar', NULL, 2),
        ('Musandam', NULL, 2),
        ('Muscat', NULL, 2),
        ('Northeastern Governorate', NULL, 2),
        ('Southeastern Governorate', NULL, 2),
        ('Zufar', NULL, 2),
        ('Al Madinah', NULL, 3),
        ('Al Jawf', NULL, 3),
        ('Al-Qassim', NULL, 3),
        ('Asir', NULL, 3),
        ('Eastern Province', NULL, 3),
        ('Ha\'il', NULL, 3),
        ('Jizan', NULL, 3),
        ('Makkah', NULL, 3),
        ('Najran', NULL, 3),
        ('Riyadh', NULL, 3),
        ('Tabuk', NULL, 3)");

        DB::unprepared("INSERT INTO `areas` (`name`, `city_id`) VALUES
        ('Abu Hail', 1),
        ('Al Awir First', 1),
        ('Al Awir Second', 1),
        ('Al Bada', 1),
        ('Al Baraha', 1),
        ('Al Barsha First', 1),
        ('Al Barsha Second', 1),
        ('Al Barsha South First', 1),
        ('Al Barsha South Second', 1),
        ('Al Barsha South Third', 1),
        ('Al Barsha Third', 1),
        ('Al Buteen', 1),
        ('Al Dhagaya', 1),
        ('Al Garhoud', 1),
        ('Al Guoz Fourth', 1),
        ('Al Hamriya', 1),
        ('Al Hamriya Port', 1),
        ('Al Hudaiba', 1),
        ('Al Jaddaf', 1),
        ('Al Jafiliya', 1),
        ('Al Karama', 1),
        ('Al Khabaisi', 1),
        ('Al Khwaneej First', 1),
        ('Al Khwaneej Second', 1),
        ('Al Kifaf', 1),
        ('Al Mamzar', 1),
        ('Al Manara', 1),
        ('Al Merkad', 1),
        ('Al Mina', 1),
        ('Al Mizhar First', 1),
        ('Al Mizhar Second', 1),
        ('Al Muraqqabat', 1),
        ('Al Murar', 1),
        ('Al Sabkha', 1),
        ('Al Muteena', 1),
        ('Al Nahda First', 1),
        ('Al Nahda Second', 1),
        ('Al Quoz First', 1),
        ('Al Quoz Industrial First', 1),
        ('Al Quoz Industrial Fourth', 1),
        ('Al Quoz Industrial Second', 1),
        ('Al Quoz Industrial Third', 1),
        ('Al Quoz Second', 1),
        ('Al Quoz Third', 1),
        ('Al Qusais First', 1),
        ('Al Qusais Industrial Fifth', 1),
        ('Al Qusais Industrial First', 1),
        ('Al Qusais Industrial Fourth', 1),
        ('Al Qusais Industrial Second', 1),
        ('Al Qusais Industrial Third', 1),
        ('Al Qusais Second', 1),
        ('Al Qusais Third', 1),
        ('Al Raffa', 1),
        ('Al Ras', 1),
        ('Al Rashidiya', 1),
        ('Al Rigga', 1),
        ('Al Safa First', 1),
        ('Al Safa Second', 1),
        ('Al Safouh First', 1),
        ('Al Safouh Second', 1),
        ('Al Satwa', 1),
        ('Al Shindagha', 1),
        ('Al Souq Al Kabeer', 1),
        ('Al Twar First', 1),
        ('Al Twar Second', 1),
        ('Al Twar Third', 1),
        ('Al Warqa\'a Fifth', 1),
        ('Al Warqa\'a First', 1),
        ('Al Warqa\'a Fourth', 1),
        ('Al Warqa\'a Second', 1),
        ('Al Warqa\'a Third', 1),
        ('Al Wasl', 1),
        ('Al Waheda', 1),
        ('Ayal Nasir', 1),
        ('Aleyas', 1),
        ('Bu Kadra', 1),
        ('Dubai Investment park First', 1),
        ('Dubai Investment Park Second', 1),
        ('Emirates Hill First', 1),
        ('Emirates Hill Second', 1),
        ('Emirates Hill Third', 1),
        ('Hatta', 1),
        ('Hor Al Anz', 1),
        ('Hor Al Anz East', 1),
        ('Jebel Ali 7', 1),
        ('Jebel Ali 2', 1),
        ('Jebel Ali Industrial', 1),
        ('Jebel Ali Palm', 1),
        ('Jumeira First', 1),
        ('Palm Jumeira', 1),
        ('Jumeira Second', 1),
        ('Jumeira Third', 1),
        ('Al Mankhool', 1),
        ('Marsa Dubai', 1),
        ('Mirdif', 1),
        ('Muhaisanah Fourth', 1),
        ('Muhaisanah Second', 1),
        ('Muhaisanah Third', 1),
        ('Muhaisnah First', 1),
        ('Al Mushrif', 1),
        ('Nad Al Hammar', 1),
        ('Nadd Al Shiba Fourth', 1),
        ('Nadd Al Shiba Second', 1),
        ('Nadd Al Shiba Third', 1),
        ('Nad Shamma', 1),
        ('Naif', 1),
        ('Al Muteena First', 1),
        ('Al Muteena Second', 1),
        ('Al Nasr, Dubai', 1),
        ('Port Saeed', 1),
        ('Arabian Ranches', 1),
        ('Ras Al Khor', 1),
        ('Ras Al Khor Industrial First', 1),
        ('Ras Al Khor Industrial Second', 1),
        ('Ras Al Khor Industrial Third', 1),
        ('Rigga Al Buteen', 1),
        ('Trade Centre 1', 1),
        ('Trade Centre 2', 1),
        ('Umm Al Sheif', 1),
        ('Umm Hurair First', 1),
        ('Umm Ramool', 1),
        ('Umm Suqeim First', 1),
        ('Umm Suqeim Second', 1),
        ('Umm Suqeim Third', 1),
        ('Wadi Alamardi', 1),
        ('Warsan First', 1),
        ('Warsan Second', 1),
        ('Za\'abeel First', 1),
        ('Za\'abeel Second', 1),
        ('Akoya', 1),
        ('Al Furjan', 1),
        ('Akoya Oxygen', 1),
        ('Business Bay', 1),
        ('Downtown Dubai', 1),
        ('Sheikh Zayed Road', 1),
        ('International City', 1),
        ('Meydan City', 1),
        ('Abu shagara', 2),
        ('Al Brashi', 2),
        ('Al Butina', 2),
        ('Al Ettihad Street', 2),
        ('Al Ghafeyah area', 2),
        ('Al Jubail', 2),
        ('Al Khaldeia Area', 2),
        ('Al Khan', 2),
        ('Al Khezamia', 2),
        ('Al Majaz', 2),
        ('Al Mamzar - Sharjah', 2),
        ('Al Mareija', 2),
        ('Al Nahda', 2),
        ('Al Nahda', 2),
        ('Al Naimiya Area', 2),
        ('Al Nekhailat', 2),
        ('Al Nouf', 2),
        ('Al Nujoom Islands', 2),
        ('Al Qasbaa', 2),
        ('Al Qasemiya', 2),
        ('Al Ramla', 2),
        ('Al Ramtha', 2),
        ('Al Riffa Area', 2),
        ('Al Shahba', 2),
        ('Al Taawon', 2),
        ('Al Wahda', 2),
        ('Al Yarmouk', 2),
        ('Cornich Al Buhaira', 2),
        ('Halwan', 2),
        ('Hamriyah Free Zone', 2),
        ('Maysaloon', 2),
        ('Muelih', 2),
        ('Rolla Area', 2),
        ('Sharjah Airport freezone (SAIF)', 2),
        ('Sharjah Industrial Area', 2),
        ('Umm Khanoor', 2),
        ('Wasit', 2),
        ('Abu Dhabi Gate City', 3),
        ('Airport Road', 3),
        ('Al Badaa', 3),
        ('Al Bahia', 3),
        ('Al Baraha', 3),
        ('Al Bateen', 3),
        ('Al Dhafrah', 3),
        ('Al Falah City', 3),
        ('Al Ghadeer', 3),
        ('Al Hudayriat Island', 3),
        ('Al Ittihad Road', 3),
        ('Al Karama', 3),
        ('Al Khaleej Al Arabi Street', 3),
        ('Al Khalidiya', 3),
        ('Al Maffraq', 3),
        ('Al Manaseer', 3),
        ('Al Manhal', 3),
        ('Al Maqtaa', 3),
        ('Al Markaziyah', 3),
        ('Al Mina', 3),
        ('Al Mushrif', 3),
        ('Al Nahyan Camp', 3),
        ('Al Najda Street', 3),
        ('Al Qurm', 3),
        ('Al Raha Beach', 3),
        ('Al Raha Gardens', 3),
        ('Al Raha Golf Gardens', 3),
        ('Al Rahba', 3),
        ('Al Rawdah', 3),
        ('Al Reef', 3),
        ('Al Reem Island', 3),
        ('Al Ruwais', 3),
        ('Al Samha', 3),
        ('Al Shahama', 3),
        ('Al Shamkha', 3),
        ('Al Sowwah', 3),
        ('Al Wahda', 3),
        ('Al Wathba', 3),
        ('Al Zaab', 3),
        ('Baniyas', 3),
        ('Between Two Bridges', 3),
        ('Building Materials City', 3),
        ('City Downtown', 3),
        ('Corniche Area', 3),
        ('Corniche Road', 3),
        ('Danet Abu Dhabi', 3),
        ('Defence Street', 3),
        ('Desert Village', 3),
        ('Eastern Road', 3),
        ('Electra Street', 3),
        ('Ghantoot', 3),
        ('Grand Mosque District', 3),
        ('Hamdan Street', 3),
        ('Hydra Village', 3),
        ('Jawazat Street', 3),
        ('Khalifa City', 3),
        ('Khalifa Street', 3),
        ('Lulu Island', 3),
        ('Madinat Zayed', 3),
        ('Marina Village', 3),
        ('Masdar City', 3),
        ('Mohamed Bin Zayed City', 3),
        ('Muroor Area', 3),
        ('Mussafah', 3),
        ('Nurai Island', 3),
        ('Saadiyat Island', 3),
        ('Salam Street', 3),
        ('Sas Al Nakheel', 3),
        ('Tourist Club Area', 3),
        ('Umm Al Nar', 3),
        ('Yas Island', 3),
        ('Zayed Military City', 3),
        ('Zayed Sports City', 3),
        ('Al Darbijaniyah', 4),
        ('Al Dhait', 4),
        ('Al Hamra', 4),
        ('Al Hamra Village', 4),
        ('Al Hudaihbah', 4),
        ('Al Jazeera', 4),
        ('Al Juwais', 4),
        ('Al Kharan', 4),
        ('Al Nakheel', 4),
        ('Al Saih', 4),
        ('Al Seer', 4),
        ('Al Soor', 4),
        ('Al Uraibi', 4),
        ('Al Zahra', 4),
        ('Al Zaith', 4),
        ('Dafan Al Khor', 4),
        ('Dafan Al Nakheel', 4),
        ('Dahan', 4),
        ('Jazeera Al Hamra', 4),
        ('Julan', 4),
        ('Julfar', 4),
        ('Khuzam', 4),
        ('Maareed', 4),
        ('Mamourah', 4),
        ('Nakheel', 4),
        ('Old Town RAK', 4),
        ('Seih Al Burairat', 4),
        ('Seih Al Hudaibah', 4),
        ('Seih Al Uraibi', 4),
        ('Ain Ajman', 6),
        ('Ajman Corniche Road', 6),
        ('Ajman Downtown', 6),
        ('Ajman Industrial Area', 6),
        ('Ajman Marina', 6),
        ('Ajman Meadows', 6),
        ('Ajman Uptown', 6),
        ('Al Ameera Village', 6),
        ('Al Humaid City', 6),
        ('Al Ittihad Village', 6),
        ('Al Naemiyah', 6),
        ('Al Rashidiya', 6),
        ('Al Rumaila', 6),
        ('Al Zahraa', 6),
        ('Awali City', 6),
        ('Corniche Ajman', 6),
        ('Emirates City', 6),
        ('Green City', 6),
        ('Manama', 6),
        ('Marmooka City', 6),
        ('Muehat', 6),
        ('Musheiref', 6),
        ('New industrial area', 6),
        ('Park View City', 6),
        ('Al Ozaib', 7),
        ('Al Salama', 7),
        ('Manama', 7),
        ('Masfout', 7),
        ('New Salama', 7),
        ('Sheikh Khalifa City', 7),
        ('Al Faqa?a', 8),
        ('Al Buraymi', 8),
        ('Al Ain Industrial Area', 8),
        ('Al Markhaniya', 8),
        ('Al Maqam', 8),
        ('Al Manaseer', 8),
        ('Al Khabisi', 8),
        ('Al Jimi', 8),
        ('Al Jaheli', 8),
        ('Al Hili', 8),
        ('Al Mutarad', 8),
        ('Al Sinaiya', 8),
        ('Al Tawiya', 8),
        ('Tawam', 8),
        ('Zakher', 8);");
    }
}
